# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DoorDrink' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DoorDrink

  target 'DoorDrinkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DoorDrinkUITests' do
    # Pods for testing
  end

end
